with open("src/renderer/components/MediaGrid.tsx", "w", encoding="utf-8") as f:
    f.write('import React, { useState, useEffect, useRef } from "react";\n')
    f.write('import type { MediaFile } from "../../shared/types";\n')
    f.write('import { formatSize, formatDuration } from "../utils/format";\n')
    f.write('import { VirtualMediaGrid } from "./VirtualMediaGrid";\n\n')
    
    f.write('interface MediaGridProps {\n')
    f.write('  mediaList: MediaFile[];\n')
    f.write('  selectedIds?: Set<string>;\n')
    f.write('  lastSelectedId?: string | null;\n')
    f.write('  onPlay: (media: MediaFile, isCtrlClick: boolean, isShiftClick: boolean) => void;\n')
    f.write('  onDelete: (mediaIds: string[]) => void;\n')
    f.write('  onOpenFolder?: (media: MediaFile) => void;\n')
    f.write('  onEditTags?: (medias: MediaFile[]) => void;\n')
    f.write('  onRemoveFromPlaylist?: (mediaIds: string[]) => void;\n')
    f.write('  viewMode?: "list" | "grid";\n')
    f.write('  iconSize?: number;\n')
    f.write('  onIconSizeChange?: (size: number) => void;\n')
    f.write('}\n\n')
    
    f.write('interface ContextMenuState {\n')
    f.write('  visible: boolean;\n')
    f.write('  x: number;\n')
    f.write('  y: number;\n')
    f.write('  media: MediaFile | null;\n')
    f.write('}\n\n')
    
    f.write('const MIN_ICON_SIZE = 60;\n')
    f.write('const MAX_ICON_SIZE = 300;\n\n')
    
    f.write('export const MediaGrid: React.FC<MediaGridProps> = ({\n')
    f.write('  mediaList,\n')
    f.write('  selectedIds = new Set(),\n')
    f.write('  lastSelectedId: _lastSelectedId,\n')
    f.write('  onPlay,\n')
    f.write('  onDelete,\n')
    f.write('  onOpenFolder,\n')
    f.write('  onEditTags,\n')
    f.write('  onRemoveFromPlaylist,\n')
    f.write('  viewMode = "list",\n')
    f.write('  iconSize = 120,\n')
    f.write('  onIconSizeChange,\n')
    f.write('}) => {\n')
    f.write('  const [contextMenu, setContextMenu] = useState<ContextMenuState>({\n')
    f.write('    visible: false,\n')
    f.write('    x: 0,\n')
    f.write('    y: 0,\n')
    f.write('    media: null,\n')
    f.write('  });\n')
    f.write('  const [showTooltip, setShowTooltip] = useState(false);\n')
    f.write('  const menuRef = useRef<HTMLDivElement>(null);\n')
    f.write('  const containerRef = useRef<HTMLDivElement>(null);\n\n')
    
    f.write('  // 处理右键菜单\n')
    f.write('  const handleContextMenu = (e: React.MouseEvent, media: MediaFile) => {\n')
    f.write('    e.preventDefault();\n')
    f.write('    e.stopPropagation();\n')
    f.write('    setContextMenu({\n')
    f.write('      visible: true,\n')
    f.write('      x: e.clientX,\n')
    f.write('      y: e.clientY,\n')
    f.write('      media,\n')
    f.write('    });\n')
    f.write('  };\n\n')
    
    f.write('  // 关闭菜单\n')
    f.write('  const closeContextMenu = () => {\n')
    f.write('    setContextMenu(prev => ({ ...prev, visible: false }));\n')
    f.write('  };\n\n')
    
    f.write('  // 点击外部关闭菜单\n')
    f.write('  useEffect(() => {\n')
    f.write('    const handleClickOutside = () => {\n')
    f.write('      closeContextMenu();\n')
    f.write('    };\n\n')
    
    f.write('    if (contextMenu.visible) {\n')
    f.write('      document.addEventListener("click", handleClickOutside);\n')
    f.write('      return () => document.removeEventListener("click", handleClickOutside);\n')
    f.write('    }\n')
    f.write('    return undefined;\n')
    f.write('  }, [contextMenu.visible]);\n\n')
    
    f.write('  // 执行菜单操作\n')
    f.write('  const handleMenuAction = (action: "open" | "delete" | "tags" | "remove") => {\n')
    f.write('    if (!contextMenu.media) return;\n\n')
    
    f.write('    const targetIds = selectedIds.has(contextMenu.media.id)\n')
    f.write('      ? Array.from(selectedIds)\n')
    f.write('      : [contextMenu.media.id];\n\n')
    
    f.write('    switch (action) {\n')
    f.write('      case "open":\n')
    f.write('        onOpenFolder?.(contextMenu.media);\n')
    f.write('        break;\n')
    f.write('      case "delete":\n')
    f.write('        onDelete(targetIds);\n')
    f.write('        break;\n')
    f.write('      case "tags":\n')
    f.write('        onEditTags?.(targetIds.map(id => mediaList.find(m => m.id === id)).filter(Boolean) as MediaFile[]);\n')
    f.write('        break;\n')
    f.write('      case "remove":\n')
    f.write('        onRemoveFromPlaylist?.(targetIds);\n')
    f.write('        break;\n')
    f.write('    }\n')
    f.write('    closeContextMenu();\n')
    f.write('  };\n\n')
    
    f.write('  // 处理点击事件（支持多选）\n')
    f.write('  const handleMediaClick = (e: React.MouseEvent, media: MediaFile) => {\n')
    f.write('    const isCtrlClick = e.ctrlKey || e.metaKey;\n')
    f.write('    const isShiftClick = e.shiftKey;\n')
    f.write('    onPlay(media, isCtrlClick, isShiftClick);\n')
    f.write('  };\n\n')
    
    f.write('  // 处理图标大小变更\n')
    f.write('  const handleSizeChange = (newSize: number) => {\n')
    f.write('    const clampedSize = Math.max(MIN_ICON_SIZE, Math.min(MAX_ICON_SIZE, newSize));\n')
    f.write('    onIconSizeChange?.(clampedSize);\n')
    f.write('  };\n\n')
    
    f.write('  // 显示提示\n')
    f.write('  const handleMouseEnter = () => {\n')
    f.write('    setShowTooltip(true);\n')
    f.write('  };\n\n')
    
    f.write('  const handleMouseLeave = () => {\n')
    f.write('    setShowTooltip(false);\n')
    f.write('  };\n\n')
    
    f.write('  // 列表视图\n')
    f.write('  if (viewMode === "list") {\n')
    f.write('    return (\n')
    f.write('      <>\n')
    f.write('        <div className="media-grid-container p-2 space-y-1">\n')
    f.write('          {mediaList.map(media => (\n')
    f.write('            <div\n')
    f.write('              key={media.id}\n')
    f.write('              className={`\n')
    f.write('                flex items-center gap-3 p-2 rounded-lg cursor-pointer transition-all duration-200\n')
    f.write('                ${\n')
    f.write('                  selectedIds.has(media.id)\n')
    f.write('                    ? "bg-[#005FB8]/20 border border-[#005FB8] shadow-sm"\n')
    f.write('                    : "hover:bg-white/5 border border-transparent"\n')
    f.write('                }\n')
    f.write('              `}\n')
    f.write('              onClick={e => handleMediaClick(e, media)}\n')
    f.write('              onContextMenu={e => handleContextMenu(e, media)}\n')
    f.write('            >\n')
    f.write('              {/* 缩略图 */}\n')
    f.write('              <div className="w-14 h-10 bg-gray-800 rounded-lg flex-shrink-0 flex items-center justify-center overflow-hidden shadow-sm">\n')
    f.write('                {media.thumbnail ? (\n')
    f.write('                  <img\n')
    f.write('                    src={media.thumbnail}\n')
    f.write('                    alt={media.filename}\n')
    f.write('                    className="w-full h-full object-cover"\n')
    f.write('                  />\n')
    f.write('                ) : media.type === "image" ? (\n')
    f.write('                  <img\n')
    f.write('                    src={`file://${encodeURI(media.path.replace(/\\/g, "/"))}`}\n')
    f.write('                    alt={media.filename}\n')
    f.write('                    className="w-full h-full object-cover"\n')
    f.write('                  />\n')
    f.write('                ) : (\n')
    f.write('                  <span className="text-base">🎬</span>\n')
    f.write('                )}\n')
    f.write('              </div>\n\n')
    
    f.write('              {/* 信息 */}\n')
    f.write('              <div className="flex-1 min-w-0">\n')
    f.write('                <p className="text-sm truncate text-gray-100 font-medium" title={media.filename}>\n')
    f.write('                  {media.filename}\n')
    f.write('                </p>\n')
    f.write('                <p className="text-xs text-gray-400">\n')
    f.write('                  {formatSize(media.size)}\n')
    f.write('                  {media.width && media.height && ` · ${media.width}×${media.he
